@startuml
!pragma layout smetana
'https://plantuml.com/use-case-diagram

:Admin:

Admin ---> (add admin)

User --> (sign up)
Admin --> (sign in)
User --> (sign in)
(sign up) --> (registration): <<include>>

User --> (balance)
(balance) --> (withdraw): <<extend>>
(balance) --> (deposit): <<extend>>

User --> (trade)
(trade) --> (buy): <<extend>>
(trade) --> (sell): <<extend>>
(buy) --> (withdraw): <<include>>
(sell) --> (deposit): <<include>>

User --> (browse)
(browse) --> (search): <<extend>>


Admin ---> (Ban)
User -- (Ban)
(Ban) --> (banned list): <<include>>



@enduml